name: Nutrifrnd
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.2.0
  flutter_dialogflow: ^0.1.3

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.6
  url_launcher: ^5.4.7
  rflutter_alert: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/

  fonts:
  - family: Rubik
    fonts:
      - asset: fonts/Rubik-Regular.ttf

  - family: Source Sans Pro
    fonts:
      - asset: fonts/SourceSansPro-SemiBold.ttf

  - family: Basic
    fonts:
      - asset: fonts/Basic-Regular.ttf

  - family: Courgette
    fonts:
      - asset: fonts/Courgette-Regular.ttf

  - family: OleoScript
    fonts:
      - asset: fonts/OleoScript-Regular.ttf

  - family: Philosopher
    fonts:
      - asset: fonts/Philosopher-Bold.ttf